---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: gpbackup
  type: git
  source:
    uri: https://github.com/greenplum-db/gpbackup
    branch: master

- name: gpdb_src
  type: git
  source:
    uri: https://github.com/greenplum-db/gpdb
    branch: 5X_STABLE
    tag_filter: 5.*

- name: bin_gpdb_master
  type: s3
  source:
      bucket: gpdb5-assert-concourse-builds
      versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{bucket-access-key-id}}
      secret_access_key: {{bucket-secret-access-key}}

- name: bin_gpdb_5x_stable
  type: s3
  source:
      bucket: gpdb5-release-builds
      versioned_file: bin_gpdb_centos6/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{bucket-access-key-id}}
      secret_access_key: {{bucket-secret-access-key}}

- name: bin_gpdb_43_stable
  type: s3
  source:
      bucket: gpdb-4.3-release
      versioned_file: bin_gpdb_centos5/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{gpdb4-bucket-access-key-id}}
      secret_access_key: {{gpdb4-bucket-secret-access-key}}

- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}
    tag_filter: 1.4.10

- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      bucket: gpdb5-pipeline-dynamic-terraform
      bucket_path: prod/gpbackup/

- name: boostfs_terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{gpdb4-tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{gpdb4-tf-machine-secret-access-key}}
    storage:
      access_key_id: {{gpdb4-tf-machine-access-key-id}}
      secret_access_key: {{gpdb4-tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      bucket: pivotal-pa-toolsmiths-pipeline-dynamic-terraform
      bucket_path: {{tf-bucket-path}}

- name: scale_schema
  type: s3
  source:
    access_key_id: {{gpdb4-bucket-access-key-id}}
    bucket: {{netbackup_installer_bucket}}
    region_name: {{aws-region}}
    secret_access_key: {{gpdb4-bucket-secret-access-key}}
    versioned_file: scale-schemas/scale_db1.tgz

- name: boostfs_installer
  type: s3
  source:
    access_key_id: {{gpdb4-bucket-access-key-id}}
    bucket: {{netbackup_installer_bucket}}
    region_name: {{aws-region}}
    secret_access_key: {{gpdb4-bucket-secret-access-key}}
    versioned_file: DDBoostFS-1.1.0.1-565598.rhel.x86_64.rpm

jobs:
- name: units
  plan:
  - aggregate:
    - get: gpbackup
      trigger: true
  - task: unit-tests
    file: gpbackup/ci/tasks/unit-tests.yml

- name: integrations-master
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ccp"]
      trigger: true
    - get: bin_gpdb_master
      tags: ["ccp"]
    - get: ccp_src
      tags: ["ccp"]
    - get: gpdb_src
      tags: ["ccp"]
  - put: terraform
    tags: ["ccp"]
    params:
      <<: *ccp_create_params
      vars:
        <<: *ccp_default_vars
  - task: gen_cluster
    tags: ["ccp"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
    input_mapping:
      gpdb_binary: bin_gpdb_master
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    tags: ["ccp"]
    file: gpbackup/ci/tasks/integration-tests.yml
    on_success:
      <<: *ccp_destroy
    on_failure:
      <<: *set_failed
  ensure:
    <<: *set_failed

- name: integrations-GPDB5
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ccp"]
      trigger: true
    - get: bin_gpdb_5x_stable
      tags: ["ccp"]
    - get: ccp_src
      tags: ["ccp"]
    - get: gpdb_src
      tags: ["ccp"]
  - put: terraform
    tags: ["ccp"]
    params:
      <<: *ccp_create_params
      vars:
        <<: *ccp_default_vars
  - task: gen_cluster
    params:
      <<: *ccp_gen_cluster_default_params
    tags: ["ccp"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_5x_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    tags: ["ccp"]
    file: gpbackup/ci/tasks/integration-tests.yml
    on_success:
      <<: *ccp_destroy
    on_failure:
      <<: *set_failed
  ensure:
    <<: *set_failed

- name: integrations-GPDB4.3
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ccp"]
      trigger: true
    - get: bin_gpdb_43_stable
      tags: ["ccp"]
    - get: ccp_src
      tags: ["ccp"]
    - get: gpdb_src
      tags: ["ccp"]
  - put: terraform
    tags: ["ccp"]
    params:
      <<: *ccp_create_params
      vars:
        <<: *ccp_default_vars
  - task: gen_cluster
    params:
      <<: *ccp_gen_cluster_default_params
    tags: ["ccp"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_43_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    tags: ["ccp"]
    file: gpbackup/ci/tasks/integration-tests.yml
    on_success:
      <<: *ccp_destroy
    on_failure:
      <<: *set_failed
  ensure:
    <<: *set_failed

- name: scale-master
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ccp"]
    - get: bin_gpdb_master
      tags: ["ccp"]
    - get: ccp_src
      tags: ["ccp"]
    - get: gpdb_src
      tags: ["ccp"]
    - get: scale_schema
      tags: ["ccp"]
  - put: terraform
    tags: ["ccp"]
    params:
      <<: *ccp_create_params
      terraform_source: ccp_src/aws-nvme-block-device/
      vars:
        aws_instance-node-instance_type: i3.large
        aws_ebs_volume_type: gp2
        number_of_nodes: 1
  - task: gen_cluster
    params:
      <<: *ccp_gen_cluster_default_params
    tags: ["ccp"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_master
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: scale-tests
    tags: ["ccp"]
    file: gpbackup/ci/tasks/scale-tests.yml
    on_success:
      <<: *ccp_destroy
    on_failure:
      <<: *set_failed
  ensure:
    <<: *set_failed

# This job has a different configuration because it is set up for use with boostfs
- name: scale-5x-stable
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ddboost"]
    - get: bin_gpdb_5x_stable
      tags: ["ddboost"]
    - get: ccp_src
      tags: ["ddboost"]
    - get: gpdb_src
      tags: ["ddboost"]
    - get: scale_schema
      tags: ["ddboost"]
    - get: boostfs_installer
      tags: ["ddboost"]
  - put: boostfs_terraform
    tags: ["ddboost"]
    params:
      <<: *ccp_create_params
      terraform_source: ccp_src/aws-pivotal-pa-toolsmiths/
      vars:
        aws_instance-node-instance_type: m4.large
        aws_ebs_volume_type: gp2
        aws_ebs_volume_size: 128
        number_of_nodes: 3
  - task: gen_cluster
    params:
      <<: *boostfs_ccp_gen_cluster_default_params
    tags: ["ddboost"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      terraform: boostfs_terraform
      gpdb_binary: bin_gpdb_5x_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *boostfs_ccp_destroy
  - task: boostfs_installation
    tags: ["ddboost"]
    config:
      platform: linux
      inputs:
       - name: ccp_src
       - name: cluster_env_files
       - name: boostfs_installer
       - name: gpbackup
      image_resource:
        type: docker-image
        source:
          repository: pivotaldata/ccp
          tag: '7'
      run:
        path: bash
        args:
        - -c
        - |
          set -ex
          ccp_src/aws/setup_ssh_to_cluster.sh
          export DD_IP={{datadomain_source_host}}
          export DD_USER={{datadomain_user}}
          export DD_PASSWORD={{datadomain_password}}
          chmod +x gpbackup/ci/scripts/setup_boostfs.sh
          gpbackup/ci/scripts/setup_boostfs.sh
    on_failure:
      <<: *boostfs_debug_sleep

  - task: scale-tests
    tags: ["ddboost"]
    file: gpbackup/ci/tasks/scale-tests.yml
    on_failure:
      <<: *boostfs_debug_sleep
  - *boostfs_ccp_destroy

- name: scale-43-stable
  plan:
  - aggregate:
    - get: gpbackup
      tags: ["ccp"]
    - get: bin_gpdb_43_stable
      tags: ["ccp"]
    - get: ccp_src
      tags: ["ccp"]
    - get: gpdb_src
      tags: ["ccp"]
    - get: scale_schema
      tags: ["ccp"]
  - put: terraform
    tags: ["ccp"]
    params:
      <<: *ccp_create_params
      terraform_source: ccp_src/aws-nvme-block-device/
      vars:
        aws_instance-node-instance_type: i3.large
        aws_ebs_volume_type: gp2
        number_of_nodes: 1
  - task: gen_cluster
    params:
      <<: *ccp_gen_cluster_default_params
    tags: ["ccp"]
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_43_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: scale-tests
    tags: ["ccp"]
    file: gpbackup/ci/tasks/scale-tests.yml
    on_success:
      <<: *ccp_destroy
    on_failure:
      <<: *set_failed
  ensure:
    <<: *set_failed

ccp_create_params_anchor: &ccp_create_params
  action: create
  delete_on_failure: true
  generate_random_name: true
  terraform_source: ccp_src/aws/

ccp_vars_anchor: &ccp_default_vars
  aws_instance-node-instance_type: t2.medium
  aws_ebs_volume_type: standard
  platform: centos6

ccp_gen_cluster_default_params_anchor: &ccp_gen_cluster_default_params
  AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
  AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
  AWS_DEFAULT_REGION: {{aws-region}}
  BUCKET_NAME: gpdb5-pipeline-dynamic-terraform
  BUCKET_PATH: prod/gpbackup/

boostfs_ccp_gen_cluster_default_params_anchor: &boostfs_ccp_gen_cluster_default_params
  AWS_ACCESS_KEY_ID: {{gpdb4-tf-machine-access-key-id}}
  AWS_SECRET_ACCESS_KEY: {{gpdb4-tf-machine-secret-access-key}}
  AWS_DEFAULT_REGION: {{aws-region}}
  BUCKET_PATH: {{tf-bucket-path}}
  BUCKET_NAME: pivotal-pa-toolsmiths-pipeline-dynamic-terraform

ccp_destroy_anchor: &ccp_destroy
  put: terraform
  tags: ["ccp"]
  params:
    action: destroy
    env_name_file: terraform/name
    terraform_source: ccp_src/aws/
    vars:
      aws_instance-node-instance_type: t2.micro
  get_params:
    action: destroy

boostfs_ccp_destroy_anchor: &boostfs_ccp_destroy
  put: boostfs_terraform
  params:
    action: destroy
    env_name_file: boostfs_terraform/name
    terraform_source: ccp_src/aws-pivotal-pa-toolsmiths/
    vars:
      aws_instance-node-instance_type: t2.micro #t2.micro is ignored in destroy, but aws_instance-node-instance_type is required.
  get_params:
    action: destroy

set_failed_anchor: &set_failed
  do:
  - task: on_failure_set_failed
    tags: ["ccp"]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: toolsmiths/ccp
          tag: "7"
      inputs:
        - name: ccp_src
        - name: terraform
      run:
        path: 'ccp_src/aws/ccp_failed_test.sh'
      params:
        AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
        AWS_DEFAULT_REGION: {{tf-machine-region}}
        BUCKET_PATH: {{tf-bucket-path}}
        BUCKET_NAME: {{tf-bucket-name}}

boostfs_debug_sleep_anchor: &boostfs_debug_sleep
  do:
  - task: debug_sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      run:
        path: 'sh'
        args: ['-c', 'sleep 2h']
    ensure:
      <<: *boostfs_ccp_destroy
