name: gpbackup_go_build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, edited, ready_for_review ]

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: go/pkg/mod/github.com/cloudberrydb/gpbackup

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.4

    - name: Set Environment
      run: |
        echo "GOPATH=/home/runner/work/gpbackup/gpbackup/go" >> $GITHUB_ENV
        echo "/home/runner/work/gpbackup/gpbackup/go/bin" >> $GITHUB_PATH

    - name: Dependencies
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make depend

    - name: Build
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make build

    - name: Unit Test
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make test
